---
title: "Clustering ATTOM Real Estates Data"
author: "Prasenjeet Madhav Gadhe"
date: "2023-02-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("NbClust")
#install.packages("stylo")
#install.packages("philentropy")
#install.packages("mclust")
#install.packages("amap")
#install.packages("factoextra")
#install.packages("SnowballC")
#install.packages("caTools")
#install.packages("textstem")
#install.packages("wordcloud")
#install.packages("tm")
#install.packages("cluster")
```

```{r}
library(stats)
library(NbClust)
library(cluster)
library(mclust)

library(amap)  ## for using Kmeans (notice the cap K)

library(factoextra) ## for cluster vis, silhouette, etc.
library(purrr)
library(SnowballC)
library(caTools)
library(dplyr)
library(textstem)
library(stringr)
library(wordcloud)
library(tm) ## to read in corpus (text data)
```


```{r}
Record_3D_DF <- read.csv("Attom_Data_Clean.csv")
head(Record_3D_DF)
dim(Record_3D_DF)
```
### Removing the Qualitative attributes
```{r}
col_clus <- c("building.size.bldgsize", "building.size.groundfloorsize", "assessment.market.mktttlvalue", "assessment.tax.taxamt", "location.latitude", "location.longitude", "building.size.bldgsize", "building.parking.prkgSize", "assessment.assessed.assdimprvalue", "assessment.market.mktttlvalue", "assessment.tax.taxamt")
#col_clus <- c("building.size.bldgsize")
Record_3D_DF <- Record_3D_DF[col_clus]
Record_3D_DF <- na.omit(Record_3D_DF)
Record_3D_DF[] <- apply(Record_3D_DF, 2, as.numeric)
Record_3D_DF
dim(Record_3D_DF)
```
### Saving the Dataframe to CSV for backup

```{r}
write.csv(Record_3D_DF, "Attom_Clust.csv")
```

```{r}
summary(Record_3D_DF)
```

### Normalizing the data
```{r}
Record_3D_DF[] <- lapply(Record_3D_DF, as.numeric)

Record_3D_DF_Norm <- as.data.frame(scale(Record_3D_DF))
```

### Finding the number of clusters using Silhouette Method

```{r}
fviz_nbclust(Record_3D_DF_Norm, method = "silhouette", 
             FUN = hcut, k.max = 5)
```

```{r}
## Look at scaled distances
(Dist_norm<- dist(Record_3D_DF_Norm, method = "minkowski", p=2)) #Euclidean
```

### Finding the number of clusters using Elbow Method
```{r}
## Elbow Method (WSS - within sum sq)
############################# Elbow Methods ###################

fviz_nbclust(
  as.matrix(Record_3D_DF_Norm), 
  kmeans, 
  k.max = 5,
  method = "wss",
  diss = get_dist(as.matrix(Record_3D_DF_Norm), method = "manhattan")
)

```

### 2 Clustered Classification
```{r}
##########################
## k means..............
######################################
kmeans_3D_1_Result <- kmeans(Record_3D_DF, 2, nstart=25)   
## I could have used the normalized data - which is better to use
## But - by using the non-norm data, the results make more visual
## sense - which also matters.

# Print the results
print(kmeans_3D_1_Result)

kmeans_3D_1_Result$centers  

aggregate(Record_3D_DF, 
          by=list(cluster=kmeans_3D_1_Result$cluster), mean)

## Compare to the labels
#table(Record_3D_DF_all$Label, kmeans_3D_1_Result$cluster)
## This is a confusion matrix
```

```{r}
summary(kmeans_3D_1_Result)
## cluster  10  means that there are 10 points all placed
## into a cluster. In our case, 5 in one and 5 in the other.
## Centers: 6    The 6 means that each of the 2 centers is 3D
## This is NOT intuative!!
## size:  2   for 2 clusters
## More about the other measures...
## https://www.datanovia.com/en/lessons/k-means-clustering-in-r-algorith-and-practical-examples/
##

## Place results in a tbale with the original data
#cbind(Record_3D_DF_all, cluster = kmeans_3D_1_Result$cluster)

## See each cluster
kmeans_3D_1_Result$cluster

## This is the size (the number of points in) each cluster
# Cluster size
kmeans_3D_1_Result$size
## Here we have two clusters, each with 5 points (rows/vectors) 

## Visualize the clusters
fviz_cluster(kmeans_3D_1_Result, Record_3D_DF, main="Euclidean")
```
### 3 Clustered Classification
```{r}
##########################
## k means..............
######################################
kmeans_3D_1_Result <- kmeans(Record_3D_DF, 3, nstart=25)   
## I could have used the normalized data - which is better to use
## But - by using the non-norm data, the results make more visual
## sense - which also matters.

# Print the results
print(kmeans_3D_1_Result)

kmeans_3D_1_Result$centers  

aggregate(Record_3D_DF, 
          by=list(cluster=kmeans_3D_1_Result$cluster), mean)

## Compare to the labels
#table(Record_3D_DF_all$Label, kmeans_3D_1_Result$cluster)
## This is a confusion matrix
```

```{r}
summary(kmeans_3D_1_Result)
## cluster  10  means that there are 10 points all placed
## into a cluster. In our case, 5 in one and 5 in the other.
## Centers: 6    The 6 means that each of the 2 centers is 3D
## This is NOT intuative!!
## size:  2   for 2 clusters
## More about the other measures...
## https://www.datanovia.com/en/lessons/k-means-clustering-in-r-algorith-and-practical-examples/
##

## Place results in a tbale with the original data
#cbind(Record_3D_DF_all, cluster = kmeans_3D_1_Result$cluster)

## See each cluster
kmeans_3D_1_Result$cluster

## This is the size (the number of points in) each cluster
# Cluster size
kmeans_3D_1_Result$size
## Here we have two clusters, each with 5 points (rows/vectors) 

## Visualize the clusters
fviz_cluster(kmeans_3D_1_Result, Record_3D_DF, main="Euclidean")
```

### 4 Clustered Classification
```{r}
##########################
## k means..............
######################################
kmeans_3D_1_Result <- kmeans(Record_3D_DF, 4, nstart=25)   
## I could have used the normalized data - which is better to use
## But - by using the non-norm data, the results make more visual
## sense - which also matters.

# Print the results
print(kmeans_3D_1_Result)

kmeans_3D_1_Result$centers  

aggregate(Record_3D_DF, 
          by=list(cluster=kmeans_3D_1_Result$cluster), mean)

## Compare to the labels
#table(Record_3D_DF_all$Label, kmeans_3D_1_Result$cluster)
## This is a confusion matrix
```

```{r}
summary(kmeans_3D_1_Result)
## cluster  10  means that there are 10 points all placed
## into a cluster. In our case, 5 in one and 5 in the other.
## Centers: 6    The 6 means that each of the 2 centers is 3D
## This is NOT intuative!!
## size:  2   for 2 clusters
## More about the other measures...
## https://www.datanovia.com/en/lessons/k-means-clustering-in-r-algorith-and-practical-examples/
##

## Place results in a tbale with the original data
#cbind(Record_3D_DF_all, cluster = kmeans_3D_1_Result$cluster)

## See each cluster
kmeans_3D_1_Result$cluster

## This is the size (the number of points in) each cluster
# Cluster size
kmeans_3D_1_Result$size
## Here we have two clusters, each with 5 points (rows/vectors) 

## Visualize the clusters
fviz_cluster(kmeans_3D_1_Result, Record_3D_DF, main="Euclidean")
```

## Hirarchical Clustering

```{r}
# Dissimilarity matrix
d <- dist(Record_3D_DF, method = "euclidean")

# Hierarchical clustering using Complete Linkage
hc1 <- hclust(d, method = "complete" )

# Plot the obtained dendrogram
plot(hc1, cex = 0.5, hang = -1)
```
